[project]
name = "obsidian-rag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "einops>=0.8.1",
    "llama-index>=0.12.40",
    "llama-index-embeddings-huggingface>=0.5.4",
    "sentence-transformers>=4.1.0",
]
